apiVersion: 1

datasources:
  - name: InfluxDB-Industrial
    type: influxdb
    access: proxy
    url: https://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: industrial
      defaultBucket: factory
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-admin-token-2024
    editable: true
